[[onnxruntime_cpu]]
arch = "x86_64"
git-tree-sha1 = "8537307691275bdf5dd2c646e3775649643ccecf"
lazy = true
os = "windows"

    [[onnxruntime_cpu.download]]
    sha256 = "0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5"
    url = "https://github.com/microsoft/onnxruntime/releases/download/v1.20.1/onnxruntime-win-x64-1.20.1.tgz"
[[onnxruntime_cpu]]
arch = "x86_64"
git-tree-sha1 = "f449f6728afcfc4e1d18a33685f337de62732011"
lazy = true
libc = "glibc"
os = "linux"

    [[onnxruntime_cpu.download]]
    sha256 = "67db4dc1561f1e3fd42e619575c82c601ef89849afc7ea85a003abbac1a1a105"
    url = "https://github.com/microsoft/onnxruntime/releases/download/v1.20.1/onnxruntime-linux-x64-1.20.1.tgz"
[[onnxruntime_cpu]]
arch = "x86_64"
git-tree-sha1 = "e83647aba10d99e20321ad123cb92974fee357dc"
lazy = true
os = "macos"

    [[onnxruntime_cpu.download]]
    sha256 = "da4349e01a7e997f5034563183c7183d069caadc1d95f499b560961787813efd"
    url = "https://github.com/microsoft/onnxruntime/releases/download/v1.20.1/onnxruntime-osx-universal2-1.20.1.tgz"
[[onnxruntime_cpu]]
arch = "aarch64"
git-tree-sha1 = "3aaa741ff710a21c23370cda7d967939dfc82e6a"
lazy = true
os = "macos"

    [[onnxruntime_cpu.download]]
    sha256 = "b678fc3c2354c771fea4fba420edeccfba205140088334df801e7fc40e83a57a"
    url = "https://github.com/microsoft/onnxruntime/releases/download/v1.20.1/onnxruntime-osx-arm64-1.20.1.tgz"

[[onnxruntime_gpu]]
arch = "x86_64"
git-tree-sha1 = "09c70e5af145d9c84cada2cbda13ff07e18a1dbc"
lazy = true
os = "windows"

    [[onnxruntime_gpu.download]]
    sha256 = "3e9658d4aa7c21b3f5cbb5a7ce0356184f3c183c317b52f9cfff23a3f079634e"
    url = "https://github.com/microsoft/onnxruntime/releases/download/v1.20.1/onnxruntime-win-x64-gpu-1.20.1.zip"
[[onnxruntime_gpu]]
arch = "x86_64"
git-tree-sha1 = "a6b97c24aaf0f98fb899dc4cb4e076fb4e3bf2a8"
lazy = true
libc = "glibc"
os = "linux"

    [[onnxruntime_gpu.download]]
    sha256 = "6bfb87c6ebe55367a94509b8ef062239e188dccf8d5caac8d6909b2344893bf0"
    url = "https://github.com/microsoft/onnxruntime/releases/download/v1.20.1/onnxruntime-linux-x64-gpu-1.20.1.tgz"
